### ISSUE TITLE
unused variables

### ISSUE THREAD

**Issue by tborychowski** [kangax/jscritic#18] opened 2014-04-14 14:24 UTC
I believe it detects unused variables incorrectly, e.g.:

``` javascript
$('.selector').each(function (idx, el) {
    console.log(el);
});
```

In this example `idx` is counted as an unused variable (which is the case, but there is no other (clean) way of using the second without declaring the first).
Moreover, jshint doesn't count `idx` as an unused var in this case.

Thanks!

**Comment by kangax** [comment] 2014-04-14 15:43
Duplicate of #1 (depends on https://github.com/jshint/jshint/issues/1605)

**Closed as completed by kangax** 2014-04-14 15:43 UTC
